version: '3'

services:
  frontend:
    image: fronend-dev:latest
    networks:
      - frontend_network
    extra_hosts:
      - "dev-api-imsv2.nccsoft.vn:192.168.56.22"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx/fe-dev:/var/log/nginx
      
networks:
  frontend_network:
    name: gateway_network
    external: true
    