version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.fe-stg
    image: frontend-stg:v1
    restart: unless-stopped
    networks:
      - frontend_network
    extra_hosts:
      - "stg-api-imsv2.nccsoft.vn:192.168.56.22"
    volumes:
      - ./nginx.stg.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx/fe-stg:/var/log/nginx

networks:
  frontend_network:
    name: gateway_network
    external: true
    