version: '3'
services:
    backend:
      image: backend-dev:latest
      tty: true
      networks:
        - backend_network

networks:
  backend_network:
    name: gateway_network
    external: true
          