version: '3'
services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile.stg
      image: backend-stg:v1
      restart: unless-stopped
      tty: true
      networks:
        - backend_network

networks:
  backend_network:
    name: gateway_network
    external: true
          