version: '3'
services:
    backend:
        image: python:3.12.0b4-slim-bullseye
        restart: unless-stopped
        tty: true
        expose:
          - "3000"
        networks:
          - backend_network

networks:
  backend_network:
    name: gateway_network
    external: true
          